version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend/app:/app/app
      - ./backend/sqlbackup.db:/app/sqlbackup.db
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:80"
    depends_on:
      - backend 